---
- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  become: yes

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  become: yes

- name: Update sshd_config with new port number
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ ssh.port }}"
    state: present
    backup: yes
  become: yes

- name: Reload sshd to apply new configuration
  ansible.builtin.systemd:
    name: sshd
    state: reloaded
  become: yes
