---
- name: Upgrade packages
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 300
  become: yes

- name: Install packages
  apt:
    name:
      - ufw
    state: present
    update_cache: yes
  become: yes

- name: Enable firewall
  become: yes
  ufw:
    state: enabled
    policy: deny

- name: Allow WWW Full (HTTP and HTTPS)
  become: yes
  ufw:
    rule: allow
    name: "WWW Full"

- name: Allow SSH
  become: yes
  ufw: rule=allow port={{ ssh.port }} proto=tcp
