---
- name: Upgrade packages
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 300
  become: yes

- name: Install packages
  apt:
    name:
      - fail2ban
    state: present
    update_cache: yes
  become: yes

- name: Update SSH port in Fail2Ban
  lineinfile:
    path: /etc/fail2ban/jail.local
    regexp: "^port[ ]*=[ ]*ssh"
    line: "port = {{ ssh.port }}"
    state: present
    create: yes
  become: yes
  notify: restart fail2ban
